### ISSUE TITLE
IllegalStateException in org.eclipse.m2e.wtp.internal.filtering.ResourceFilteringBuildParticipant.executeCopyResources

### ISSUE THREAD

**Issue by theit** [eclipse-m2e/m2e-wtp#13]
As already reported here: https://github.com/eclipse-m2e/m2e-core/issues/867

Eclipse IDE for Java Developers 2022-09 M2 (4.25.0 M2, 20220804-1257)
m2e: 2.0.1.20220805-1816
m2e-wtp: 1.5.0.20220805-2025

Create a new empty project of type "General" and in the project a new file pom.xml having the following contents (no other files necessary):

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.example</groupId>
	<artifactId>test</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>war</packaging>


	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.10.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<version>3.3.2</version>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<version>3.1.0</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>
</project>
```

Right-click on the project -> Configure -> Convert to Maven Project. Result:
Line 7 (the one with packaging=war) is marked with an error, and the description says:

Conflicting lifecycle mapping metadata (project packaging type="war"): Mapping defined in 'org.eclipse.m2e.jdt_2.0.0.20220706-1958 [834]' and 'org.eclipse.m2e.wtp_1.5.0.20220805-2025 [1023]'. To enable full functionality, remove the conflicting mapping and run Maven->Update Project Configuration.

Ignoring the m2e-wtp one results in the behaviour reported in https://github.com/eclipse-m2e/m2e-core/issues/867 (no facets/natures added). When I ignore the one from m2e-core, then m2e-wtp seems to add the facets and natures, but two different errors now appear in the problems view:

Description: null (org.apache.maven.plugins:maven-war-plugin:3.3.2:war:default-war:package)

java.lang.IllegalStateException
at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.getSession(MavenExecutionContext.java:364)
at org.eclipse.m2e.wtp.internal.filtering.ResourceFilteringBuildParticipant.executeCopyResources(ResourceFilteringBuildParticipant.java:275)
at org.eclipse.m2e.wtp.internal.filtering.ResourceFilteringBuildParticipant.build(ResourceFilteringBuildParticipant.java:98)
at org.eclipse.m2e.wtp.internal.build.WarProjectBuildParticipant.build(WarProjectBuildParticipant.java:52)
at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:135)
at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:168)
at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$1(MavenBuilder.java:113)
at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:350)
at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:219)
at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:104)
at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:350)
at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:262)
at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:205)
at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:87)
at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:197)
at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1024)
at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:254)
at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:311)
at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:400)
at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:403)
at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:514)
at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:462)
at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:544)
at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:161)
at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:255)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Resource: pom.xml
Path: /test
Location: line 21
Type: Maven Build Problem

Description: Unknown
Resource: pom.xml
Path: /test
Location: line 1
Type: Maven Java EE Configuration Problem

The sample test project can be converted flawlessly to a Maven project with Eclipse IDE for Enterprise Java and Web Developers 2022-09 M2 (4.25.0 M2) that uses m2e-core 1.20.1.20220227-1319 and m2e-wtp 1.4.4.20201128-1705.

**Comment by mickaelistria** [comment]
Would you be willing to provide a patch that fixes it?

**Comment by mickaelistria** [comment]
This should now be fixed in latest snapshots and release.

**Comment by theit** [comment]
Sorry, I was in vacation for the last couple of weeks so I haven't seen your message...
Yes, with the latest versions this bug is fixed.

**Comment by mickaelistria** [comment]
Thanks for confirming!
