### ISSUE TITLE
Error with war packaging since m2e 2.2.0.20230228

### ISSUE THREAD

**Issue by laurent149** [eclipse-m2e/m2e-wtp#23]
Since a recent m2e update (2.2.0.20230228), I'm seeing the following error on all my projects using maven-war-plugin:

        Failed to execute mojo org.apache.maven.plugins:maven-resources-plugin:3.2.0:copy-resources {execution: default-cli} (org.apache.maven.plugins:maven-war-plugin:3.3.2:war:default-war:package)
        
        org.eclipse.core.runtime.CoreException: Failed to execute mojo org.apache.maven.plugins:maven-resources-plugin:3.2.0:copy-resources {execution: default-cli}
        	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeMojo(MavenExecutionContext.java:340)
        	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.lambda$0(MavenExecutionContext.java:291)
        	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:374)
        	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
        	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:290)
        	at org.eclipse.m2e.wtp.internal.filtering.ResourceFilteringBuildParticipant.executeCopyResources(ResourceFilteringBuildParticipant.java:271)
        	at org.eclipse.m2e.wtp.internal.filtering.ResourceFilteringBuildParticipant.build(ResourceFilteringBuildParticipant.java:94)
        	at org.eclipse.m2e.wtp.internal.build.WarProjectBuildParticipant.build(WarProjectBuildParticipant.java:52)
        	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.lambda$1(MavenBuilderImpl.java:139)
        	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:729)
        	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:122)
        	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:164)
        	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
        	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$1(MavenBuilder.java:109)
        	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:374)
        	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:228)
        	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:100)
        	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:374)
        	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
        	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:214)
        	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:83)
        	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:192)
        	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1020)
        	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
        	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:247)
        	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
        	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:392)
        	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
        	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:395)
        	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:506)
        	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:454)
        	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:536)
        	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:196)
        	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:289)
        	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
        Caused by: org.apache.maven.plugin.PluginParameterException: The parameters 'resources', 'outputDirectory' for goal org.apache.maven.plugins:maven-resources-plugin:3.2.0:copy-resources are missing or invalid
        	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:644)
        	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:597)
        	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:124)
        	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeMojo(MavenExecutionContext.java:338)
        	... 34 more

How can I address this? Preferably without pom modifications (otherwise I have tens of projects to update).

**Comment by fbricon** [comment]
Thw Web project configurator [executes the maven-resources-plugin:copy-resources goal ](https://github.com/eclipse-m2e/m2e-wtp/blob/c67a3472319b910da864da4bb98981bd7bbe3915/org.eclipse.m2e.wtp/src/org/eclipse/m2e/wtp/internal/filtering/ResourceFilteringBuildParticipant.java#L271)when web resources filtering is enabled:

```
 <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-war-plugin</artifactId>
      <version>3.3.2</version>
      <configuration>
          <webResources>
              <resource>
                  <directory>${project.basedir}/src/main/webapp</directory>
                  <filtering>true</filtering>
              </resource>
          </webResources>
      </configuration>
  </plugin>
```

Somehow it broke with m2e 2.2.0

**Comment by fbricon** [comment]
@laeubi this was broken by https://github.com/eclipse-m2e/m2e-core/commit/5640b34fceef67bf110e5bfd23244daf9921be10#diff-796a271293c65b5cac9c04a4dccddff344e43fd10f474a5cd2992c2333325704R329

When cloning the MojoExecution, the MojoExecution configuration set by [m2e-wtp](https://github.com/eclipse-m2e/m2e-wtp/blob/c67a3472319b910da864da4bb98981bd7bbe3915/org.eclipse.m2e.wtp/src/org/eclipse/m2e/wtp/internal/filtering/ResourceFilteringBuildParticipant.java#L268) is not copied over, effectively calling an incomplete mojo execution
